# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26a6ac956b18bd1cfe530cfd1b6e643c3e69cfae431a93494041c1a395d063eeae523c18a52d4d3de045ce37eaaf48b2a3b2327913f35c2fdb3156354fe50138

test:
  secret_key_base: bb92d2e6d126e9ccdb3c6f5314c8ce3617f4f6e4c3569f172fd3b55b17c01d0b6f765a6f72511d752cb43ba162028b4d8900d47a963933f2ff11ee6fbd5d528b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
